name: "jellypotato"
site-name: "jellypotato"
tagline: "A free app for Japanese learners and anyone studying for the JLPT."
description: "A free app for Japanese learners and anyone studying for the JLPT."
logo: /assets/jellypotatoiconsmall.png
image: 
  path: /assets/jellypotatoiconsmall.png
  height: 180
  width: 180
  alt: jellypotato logo
locale: en-IE
plugins:
  - jekyll-seo-tag
