name: "jellypotato"
site-name: "jellypotato"
tagline: "A free app for Japanese learners and anyone studying for the JLPT."
description: "A free app for Japanese learners and anyone studying for the JLPT."
logo: jellypotatologoheader.png
image: jellypotatologoheader.png
image:width: 300px
image:height: 140px
locale: en-IE
plugins:
  - jekyll-seo-tag
