name: "jellypotato"
site-name: "jellypotato"
tagline: "A free app for Japanese learners and anyone studying for the JLPT."
description: "A free app for Japanese learners and anyone studying for the JLPT."
logo: jellypotatologoheader.png
image: 
  path: jellypotatologoheader.png
  height: 240
  width: 70
  alt: jellypotato logo
locale: en-IE
plugins:
  - jekyll-seo-tag
